### ISSUE TITLE
Create separate function to compute disposable income

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/CGE#11]
The function  for consumer demand for commodity `i`, `CGE_equations.eqXp()`, is given as:
```
Xp = alpha * ((pf * Ff).sum() - Sp - Td - Fsh + Trf) / pq
```
The term in brackets, `((pf * Ff).sum() - Sp - Td - Fsh + Trf)` is equal to `I`.

It might be easier to think about how this function matches up to the theory if `I` were computed in a separate function and passed to the `eqXp()` equation.

**Comment by duncanhobbs** [comment]
Do you want me to add this function to `household.py` as well since the functions are split into separate modules?

**Comment by jdebacker** [comment]
@duncanhobbs, That'd be great.  I think we will be removing `equations.py` soon and keeping the functions in separate modules to help with organization.
