### ISSUE TITLE
Join the Policy Simulation Library?

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/CGE#13]
Hi all -- this GitHub organization (Open-Source-Economics) is becoming a home for the [Policy Simulation Library](www.policysimulationlibrary.org), and will be renamed PSLmodels on December 3rd. Starting then, we'd like for every project in PSLmodels to either be in PSL or be in the process of joining PSL. 

CGE is very welcome in PSL! If you are interested in joining, could you please let me know by Dec 3? If the project is not interested in joining, I'll help you move this repo to a different organization or remove it. 

Please let me know how you'd like to proceed -- I'll be keeping an eye on this issue, and I'm also happy to schedule a call anytime.

**Comment by jdebacker** [comment]
@MattHJensen This project is in its infancy, but we would like to join PSL.

**Comment by MattHJensen** [comment]
Thanks @jdebacker. That is wonderful news. 

Could you begin making progress towards conforming to the [PSL Criteria](https://github.com/open-source-economics/PSL/blob/master/Criteria/library_criteria.md) as it makes sense given the project's stage? 

We will devise a tagging system to indicate a project's PSL status -- whether the project is in PSL or working towards joining PSL -- and I'll check in with you to ensure that you feel the system accommodates young projects like this one. (If you have any proactive suggestions about the tagging system, please leave them over at https://github.com/open-source-economics/PSL/issues/67)

**Comment by jdebacker** [comment]
Sounds good.  We will try to conform and let you know of any issues.
