### ISSUE TITLE
Duplicate fuctions in aggregates.py

### ISSUE THREAD

**Issue by duncanhobbs** [open-source-economics/CGE#24]
In aggregates.py there are two functions for total investment [eqXg](https://github.com/PSLmodels/CGE/blob/fbcb028a84b1484b656a11417b304b3486a3ca6b/open_cge/aggregates.py#L1-L16) and [eqXXv](https://github.com/PSLmodels/CGE/blob/fbcb028a84b1484b656a11417b304b3486a3ca6b/open_cge/aggregates.py#L204-L219). Both are defined as `g * KK` (long-run growth rate multiplied by the total capital stock.

In `CGE_equations.py`, [eqXg](https://github.com/PSLmodels/CGE/blob/master/open_cge/CGE_equations.py#L188-L204) is defined as "government expenditures on commodity j"

Do you want to keep `eqXXv` as the investment function in aggregates.py and add a function `eqXg` for "government expenditures on commodity j" to government.py?

@jdebacker

**Comment by jdebacker** [comment]
@duncanhobbs Thanks for noticing this.  `eqXg` is also defined [here](https://github.com/PSLmodels/CGE/blob/fbcb028a84b1484b656a11417b304b3486a3ca6b/open_cge/government.py#L77) in `government.py`.  That's where it should be and you can delete it from `aggregates.py`.
