### ISSUE TITLE
Should `deltad` be a required argument for eqM?

### ISSUE THREAD

**Issue by duncanhobbs** [open-source-economics/CGE#27]
In `simpleCGE.py` [line 69](https://github.com/PSLmodels/CGE/blob/master/open_cge/simpleCGE.py#L69), the eq.M() function takes 8 arguments (p.gamma, p.deltam, p.deltad, p.eta, Qbar, pq, pm, p.taum).

In the function definition in [firms.py](https://github.com/PSLmodels/CGE/blob/master/open_cge/firms.py#L200), it looks like eqM() does not use `deltad` when calculating `M`.

On page 104 of the [Hashimoto text](https://ia601904.us.archive.org/13/items/TextbookOfComputableGeneralEquilibriumModellingProgrammingAndSimulations/Textbook%20of%20Computable%20General%20Equilibrium%20Modelling%2C%20Programming%20and%20Simulations.pdf), it looks as though the M equation only includes `deltam` and not `deltad`

Should `deltad` be a required argument for eqM?

@jdebacker

**Comment by jdebacker** [comment]
@duncanhobbs Good catch.  You are right - `deltad` can be removed from that function.

**Comment by jdebacker** [comment]
Resolved with PR #28
